server:
  port: 3344

spring:
  application:
    name:  microservicecloud-config
  cloud:
    config:
      server:
        git:

#          uri: git@github.com:jjcong/microservicecloud-config.git #GitHub上面的git仓库名字
          uri: https://github.com/jjcong/microservicecloud-config.git #GitHub上面的git仓库名字
          default-label: master
          username: jjcong
          password: j15005187968c
          search-paths: application
          skipSslValidation: true