server:
  port: 9527

spring:
  application:
    name: microservicecloud-zuul-gateway

# 隐藏微服务名称，使用自定义的值代替访问服务
zuul:
  prefix: /jincong
  ignored-services: "*"
  routes:
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydept/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true


info:
  app.name: jincong-microcloud
  company.name: www.jincong.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}

